# Constants defining our neural network
INPUT_SIZE = 9
PATCH_reward = 5
OUTPUT_SIZE = 5
NPROJ = 60
NP = 128
TRAIN_IMG_NUM = 6
TEST_IMG_NUM = 6
MAXITER_RECON = 30
NPixel = 128
PATCH_NUM = NPixel * NPixel
Train_NUM_total = PATCH_NUM * TRAIN_IMG_NUM
DISCOUNT_RATE = 0.99
REPLAY_MEMORY = 5000000
BATCH_SIZE = 128
TARGET_UPDATE_FREQUENCY = 15
MAX_EPISODES = 300
load_session = 0
save_session = 1

TRAIN_NUM_ITER = 10
